### ISSUE TITLE
Docker image on v0.0.3 not assumeRole

### ISSUE THREAD

**Issue by caiohasouza** [KierranM/deadmanswatch#12]
Hi,

Could you confirm that image pushed to DockerHub on v0.0.3 version is with IRSA (https://github.com/KierranM/deadmanswatch/commit/ffc9b40a961aeb3307629a1ec4a8a503c049bd19) working? I'm using this version but role is not assumed.

Regards

**Comment by KierranM** [comment]
Yeah that was my bad. I'd forgotten how I'd done dependencies in this. I've opened #14 to do a bunch of long overdue updates and also bump to 1.0.0 so I can version this properly in the future
